name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3

      - name: Export
        run: echo ${{ secrets.GPG_PRIVATE_KEY }} > gpg.key

      - name: Sleep
        run: sleep 10
