name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run unit tests
        run: make test

  testacc:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Start httpd
        run: make httpd-start

      - name: Run acceptance tests
        run: make testacc

      - name: Stop httpd
        run: make httpd-stop

  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Format check
        run: make fmtcheck

  vet:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run vet
        run: make vet

