name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3

      - name: Run unit tests
        run: make test

  testacc:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Start httpd
        run: make httpd-start

      - name: Run acceptance tests
        run: make testacc

      - name: Stop httpd
        run: make httpd-stop

  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Format check
        run: make fmtcheck

  vet:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Run vet
        run: make vet

